### ISSUE TITLE
Add breaks slots and/or day jumps as episodes

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/workshop2021-lesson-basicobjects#1]
Just a reminder, for a given topic, like  Basic physics objects in this case, it would be good to introduce the corresponding "Breaks" and "jumps to the following day" as episodes in the [schedule](https://indico.cern.ch/event/1031398/sessions/404035/#all)  For instance, currently we would need an empty episode, between 5 and 6, called "Break" and a "See you tomorrow" one between current 6 and 7.

**Comment by jmhogan** [comment]
Closing
